### ISSUE TITLE
Change Notification models are missing

### ISSUE THREAD

**Issue by nshttpd** [microsoftgraph/msgraph-sdk-go-core#95] opened 2022-06-08 23:26 UTC
The Java SDK has models for [ChangeNotification](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/ChangeNotification.java) and [ChangeNotificationCollection](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/ChangeNotificationCollection.java) to Unmarshal into when handling webhook notifications from [Subscriptions](https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/models/subscription.go), but these and other associated models seem to be missing from the Go SDK.

Is this possibly because of how the Go SDK is autogenerated that these are missing because they are not part of an API Request, but on the receiving end of data?

**Comment by baywet** [comment] 2022-06-09 14:24
Hi @nshttpd 
Thanks for reaching out and for trying the Go SDK.

You're absolutely right, these models are missing because they are not referenced by any API in the API description. And by design [kiota, our next generation SDK generator](https://github.com/microsoft/kiota), only generates the models as they are needed.

The easiest way to get those models would probably be to:
1. Take the [existing OpenAPI description](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml)
2. Add a placeholder path item that returns change notifications
3. Clear any other endpoint
4. Use Kiota to generate the models
5. Place the models in this core library under a models package (so they can also be used in beta)

Do you think this is something you'd be willing to submit a pull request for?

**Comment by rkodev** [comment] 2023-02-08 11:53
Going to close this issue as change Notifications models are currently available in v0.54 https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/models/change_notification.go

**Closed by rkodev** 2023-02-08 11:53 UTC
Labels: enhancement, help wanted
