### ISSUE TITLE
Large file upload failing with "The Content-Range header length does not match the provided number of bytes."

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-go-core#295] opened 2024-06-07 19:03 UTC
Here's my code, I'm running this on Ubuntu with Go 1.21.5. `largeFile` is `/home/jasonjoh/vacation.gif`, and `itemPath` is `Documents/vacation.gif`. I've attached vacation.gif in case the file is important.
![vacation](https://github.com/microsoftgraph/msgraph-sdk-go-core/assets/8966342/72680c08-d1c1-414f-9d0c-6b8b21b0a99c)

```go
func UploadFileToOneDrive(graphClient *graph.GraphServiceClient, largeFile string, itemPath string) {
	itemUploadProperties := models.NewDriveItemUploadableProperties()
	itemUploadProperties.SetAdditionalData(map[string]any{"@microsoft.graph.conflictBehavior": "replace"})
	uploadSessionRequestBody := drives.NewItemItemsItemCreateuploadsessionCreateUploadSessionPostRequestBody()
	uploadSessionRequestBody.SetItem(itemUploadProperties)
	myDrive, _ := graphClient.Me().Drive().Get(context.Background(), nil)

	uploadSession, _ := graphClient.Drives().
		ByDriveId(*myDrive.GetId()).
		Items().
		ByDriveItemId("root:/"+itemPath+":").
		CreateUploadSession().
		Post(context.Background(), uploadSessionRequestBody, nil)

	maxSliceSize := int64(320 * 512)
	byteStream, _ := os.Open(largeFile)
	fileUploadTask := fileuploader.NewLargeFileUploadTask[models.DriveItemable](
		graphClient.RequestAdapter,
		uploadSession,
		byteStream,
		maxSliceSize,
		models.CreateDriveItemFromDiscriminatorValue,
		nil)

	progress := func(progress int64, total int64) {
		fmt.Printf("Uploaded %d of %d bytes", progress, total)
	}

	uploadResult := fileUploadTask.Upload(progress)

	if uploadResult.GetUploadSucceeded() {
		fmt.Printf("Upload complete, item ID: %s", *uploadResult.GetItemResponse().GetId())
	} else {
		fmt.Print("Upload failed.")
	}
}
```

Using a debugging middleware I see the headers look right, but the slices are sent in a random order (i.e. the first one isn't the 0-163839 range), which causes the failure. Per [the docs](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0&preserve-view=true#upload-bytes-to-the-upload-session), slices must be sent sequentially or you will get an error.

**Comment by buechele** [comment] 2024-06-18 20:39
Upvoting this issue.

I'm running into the same issue using similar code:
```
func SampleFileUpload(graphClient *graph.GraphServiceClient, driveID string) {

	filename := "<FILENAME>"
	driveItemId := "root:/" + "<ITEMPATH>" + ":"

	// Pre 1.44.0:
	// requestBody := drives.NewItemItemsItemCreateUploadSessionPostRequestBody()
	// 1.44.0 or later:
	requestBody := drives.NewItemItemsItemCreateuploadsessionCreateUploadSessionPostRequestBody()

	uploadProperties := models.NewDriveItemUploadableProperties()
	uploadProperties.SetAdditionalData(map[string]any{"@microsoft.graph.conflictBehavior": "replace"})
	requestBody.SetItem(uploadProperties)

	uploadSessionReqBuilder := graphClient.Drives().ByDriveId(driveID).Items().ByDriveItemId(driveItemId).CreateUploadSession()
	uploadSession, err := uploadSessionReqBuilder.Post(context.Background(), requestBody, nil)
	if err != nil {
		log.Fatal(err)
	}

	errorMapping := abstractions.ErrorMappings{
		"4XX": odataerrors.CreateODataErrorFromDiscriminatorValue,
		"5XX": odataerrors.CreateODataErrorFromDiscriminatorValue,
	}

	fileDesc, _ := os.Open(filename)
	maxSlice := int64(320 * 1024)

	uploadTask := fileuploader.NewLargeFileUploadTask[models.DriveItemable](graphClient.GetAdapter(), uploadSession, fileDesc, maxSlice, models.CreateDriveItemFromDiscriminatorValue, errorMapping)

	callback := fileuploader.ProgressCallBack(func(current int64, total int64) {
		log.Println("Progress: ", current, total)
	})

	uploadResult := uploadTask.Upload(callback)
	if !uploadResult.GetUploadSucceeded() {
		log.Fatal(uploadResult.GetResponseErrors())
	}
}
```

Result:
```
[The Content-Range header length does not match the provided number of bytes.]
```

**Comment by andrueastman** [comment] 2024-07-02 11:28
> Using a debugging middleware I see the headers look right, but the slices are sent in a random order (i.e. the first one isn't the 0-163839 range), which causes the failure. Per [the docs](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0&preserve-view=true#upload-bytes-to-the-upload-session), slices must be sent sequentially or you will get an error.

@rkodev Any chance you can take a look at this? As stated this should occur in order and the use of goroutines here will not give that assurance...

https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/954f475a0dae93b8a34377818e59ce0be75c90cf/fileuploader/large_file_upload_task.go#L65

**Comment by buechele** [comment] 2024-07-11 14:52
@rkodev @andrueastman Since you are having problems with the release, I copied your fixed fileuploader code into my code base.
The issue remains and I'm still getting the error "The Content-Range header length does not match the provided number of bytes.".

**Comment by andrueastman** [comment] 2024-07-12 07:27
Re-opening for now. 

> This is happening with the above code and also with only one slice.

@buechele Any chance you can confirm the file size of the file being uploaded? Does this mean that the task fails if the file is less than the size of a single chunk?

**Comment by buechele** [comment] 2024-07-12 07:47
@andrueastman It fails if the file size is below the maxSlice size and also if the size is above.
I tried it with several sizes (bigger and smaller than maxSlice) and everything failed.
I checked the Content-Range header created within the fileuploader package and it seems to be correct.
Currently I'm clueless about the root cause. I checked the Java-API and there it worked seamless.

**Comment by andrueastman** [comment] 2024-07-15 07:35
Does this mean that this happens for all files you try to upload? 
Any chance you're in a position to grab a trace using a logging app like fiddler and grab a snapshot of the request response cycle?
Listing all the headers as well as capturing the request body would be helpful to identify where the issue could be.

**Comment by buechele** [comment] 2024-07-15 09:12
@andrueastman Yes, it fails for all files.
I took a screenshot from the PUT request. Maybe the gzip compression is the problem. The file size in this case is 4 bytes. If I inspect the body of the request it is uncompressed. So the error from the API is correct. 
<img width="812" alt="Fiddler-1" src="https://github.com/user-attachments/assets/fa2a6128-3eff-421a-9340-cbac7414da24">

**Comment by buechele** [comment] 2024-07-15 09:26
@andrueastman Short update:
The gzip compression is not handled correctly. If I hardcode "bytes 0-27/28" into the above example it works.
So the content is compressed but the content-range header is not taking this into account and sticks with the uncompressed values.

**Comment by buechele** [comment] 2024-07-15 09:37
@andrueastman It's even worse: The originally uncompressed file which is now being uploaded without an error (by manipulating the content-range header), appears gzip compressed in the destination folder on the Microsoft side.

**Comment by andrueastman** [comment] 2024-07-15 12:19
Thanks for looking into this @buechele and getting to the root cause here.

A similar issue has been raised at https://github.com/microsoftgraph/msgraph-sdk-go/issues/747. The correct behavior should be to have data sent uncompressed to the server (I don't believe Graph api supports receiving compressed content yet). But for the client to try to decompress content from the server as it will send the accept header. 

@buechele Are you able to make this work by initialization of the graph client that has the CompressionHandler removed? 

@rkodev Any chance you can look into updating the default middleware to avoid using the default compression handler? https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/e078aab3e202c6c8e50db0019a7aa21e11e2c515/graph_client_factory.go#L12

**Comment by buechele** [comment] 2024-07-15 13:20
@andrueastman I was not able to create a graph client without compression. gzip was still on. 

But I tried this:
<img width="869" alt="Bildschirmfoto 2024-07-15 um 15 14 44" src="https://github.com/user-attachments/assets/2042cdfc-048d-4f55-b481-a20534fb5a9e">

And now I'm getting:
`The size of the provided stream is not known. Make sure the request is not chunked, and the Content-Length header is specified`

Seem like the content length header is missing this time:
<img width="826" alt="Bildschirmfoto 2024-07-15 um 15 18 50" src="https://github.com/user-attachments/assets/daba380e-1d9c-4dad-a1de-9695b00efcba">

**Comment by buechele** [comment] 2024-07-15 14:28
@andrueastman I was now able to create a graph client without compression.
I tried both ways: replacing the CompressionHandler with enableCompression = false and also to avoid to add the CompressionHandler at all to the Middleware.
Both ways are leading to the same error as mentioned in my last comment:
`The size of the provided stream is not known. Make sure the request is not chunked, and the Content-Length header is specified`

**Comment by baywet** [comment] 2024-07-15 14:53
Hi everyone,
This one sent me down a rabbit hole of RFCs for content-range and content-encoding.
Long story short: the compression middleware should not compress request bodies when a content-range header with bytes range type is present.
I tried to detailed things a bit further here https://github.com/microsoft/kiota/issues/598 and in the associated design pull request.
I believe adding the extra condition [around here](https://github.com/microsoft/kiota-http-go/blob/8a1fbc8f6b5ece80a746374f913db3a76cac9879/compression_handler.go#L77) should fix the issue end to end.
Anybody willing to submit a pull request for that?

**Comment by buechele** [comment] 2024-07-15 19:26
@baywet Maybe I understand here something wrong, but I removed, as @andrueastman suggested, the entire CompressionHandler from the pipeline and the result was, that the content-length header is now missing.
Replacing the CompressionHandler in the pipeline with enableCompression = false also leads to a missing content-length header. And in this case you are in the if-clause you are pointing out for an extra condition.
I think there is more wrong, because of the missing content-length header.

**Comment by baywet** [comment] 2024-07-15 19:52
It's strange that you're not seeing a content length header without the compression middleware as it's being set [here](https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/e078aab3e202c6c8e50db0019a7aa21e11e2c515/fileuploader/upload_slice.go#L107)
Are you seeing the content range header when you disable the compression handler?
Can you try also disabling [the redirect handler](https://github.com/microsoft/kiota-http-go/blob/8a1fbc8f6b5ece80a746374f913db3a76cac9879/redirect_handler.go#L175) for sanity?

**Comment by buechele** [comment] 2024-07-15 20:05
@baywet Yes, I ran the application in debug mode and it is set correctly in the code but missing in the actual http request.
The content-range header is included with disabled compression handler:
<img width="826" alt="Bildschirmfoto 2024-07-15 um 21 59 22" src="https://github.com/user-attachments/assets/06102326-294a-4449-91a3-f28f90ead644">
With disabled redirect handler it is also missing:
<img width="826" alt="Bildschirmfoto 2024-07-15 um 22 04 17" src="https://github.com/user-attachments/assets/37063c4b-dcba-424d-9379-077d22ed8ca2">

**Comment by baywet** [comment] 2024-07-15 20:25
Thanks for confirming, it might be the case that since this header has a dedicated field on the request object, it's not being read from the headers collection.
We might ALSO need to set the field, [like we do in the compression handler](https://github.com/microsoft/kiota-http-go/blob/8a1fbc8f6b5ece80a746374f913db3a76cac9879/compression_handler.go#L103), in the request information translation [here](https://github.com/microsoft/kiota-http-go/blob/8a1fbc8f6b5ece80a746374f913db3a76cac9879/nethttp_request_adapter.go#L297)

**Comment by baywet** [comment] 2024-07-15 20:26
Now that we have all the pieces in place, would you like to submit a pull request to:
- not compress the body when the range header is set
- set the content length field when it's present in the abstract headers

?

**Comment by baywet** [comment] 2024-07-16 11:07
Fixed by https://github.com/microsoft/kiota-http-go/pull/174
Thanks @buechele for the pull request!
Closing.

**Closed by baywet** 2024-07-16 11:07 UTC
Labels: type:bug
